export const EMPLOYEES = [
    {
      id: 1,
      name: 'Aarav Silva',
      position: 'UI UX Designer',
      category: 'Permanent',
      joinDate: '01 Sep 2023',
      location: 'Onsite',
      locationIcon: 'location_on',
      gender: 'male',
      qualification: 'Diploma',
      department: "IT",
      image: 'https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/man-user-circle-icon.png',
    },
    {
      id: 2,
      name: 'Vihaan Perera',
      position: 'Software Engineer',
      category: 'Contract',
      joinDate: '01 Sep 2023',
      location: 'Offsite',
      locationIcon: 'location_off',
      gender: 'male',
      qualification: 'Degree',
      department: "IT",
      image: 'https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/man-user-circle-icon.png',
    },
    {
      id: 3,
      name: 'Saanvi De Silva',
      position: 'Software Engineer',
      category: 'Permanent',
      joinDate: '01 Sep 2023',
      location: 'Onsite',
      locationIcon: 'location_on',
      gender: 'female',
      qualification: 'Higher Diploma',
      department: "IT",
      image: 'https://freepngimg.com/download/icon/thoughts/10268-woman-user-circle.png',
    },
    {
      id: 4,
      name: 'Riya Fernando',
      position: 'Software Engineer',
      category: 'Contract',
      joinDate: '01 Sep 2023',
      location: 'Offsite',
      locationIcon: 'location_off',
      gender: 'female',
      qualification: 'Certificate',
      department: "IT",
      image: 'https://freepngimg.com/download/icon/thoughts/10268-woman-user-circle.png',
    },
    {
      id: 5,
      name: 'Kavya Nair',
      position: 'Software Engineer',
      category: 'Contract',
      joinDate: '01 Sep 2023',
      location: 'Offsite',
      locationIcon: 'location_off',
      gender: 'female',
      qualification: 'Degree',
      department: "IT",
      image: 'https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/man-user-circle-icon.png',
    },
    {
      id: 6,
      name: 'Priya Kumar',
      position: 'Software Engineer',
      category: 'Contract',
      joinDate: '01 Sep 2023',
      location: 'Offsite',
      locationIcon: 'location_off',
      gender: 'female',
      qualification: 'Higher Diploma',
      department: "IT",
      image: 'https://freepngimg.com/download/icon/thoughts/10268-woman-user-circle.png',
    },
    {
      id: 7,
      name: 'Arjun Nair',
      position: 'Software Engineer',
      category: 'Permanent',
      joinDate: '01 Sep 2023',
      location: 'Onsite',
      locationIcon: 'location_on',
      gender: 'male',
      qualification: 'Degree',
      department: "IT",
      image: 'https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/man-user-circle-icon.png',
    },
    {
      id: 8,
      name: 'Deepika Sen',
      position: 'Software Engineer',
      category: 'Permanent',
      joinDate: '01 Sep 2023',
      location: 'Onsite',
      locationIcon: 'location_on',
      gender: 'female',
      qualification: 'Degree',
      department: "IT",
      image: 'https://freepngimg.com/download/icon/thoughts/10268-woman-user-circle.png',
    },
    {
      id: 9,
      name: 'Rahul Mehta',
      position: 'Software Engineer',
      category: 'Contract',
      joinDate: '01 Sep 2023',
      location: 'Offsite',
      locationIcon: 'location_off',
      gender: 'male',
      qualification: 'Certificate',
      department: "IT",
      image: 'https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/man-user-circle-icon.png',
    },
    {
      id: 10,
      name: 'Maya Iyer',
      position: 'Software Engineer',
      category: 'Contract',
      joinDate: '01 Sep 2023',
      location: 'Offsite',
      locationIcon: 'location_off',
      gender: 'female',
      qualification: 'Higher Diploma',
      department: "IT",
      image: 'https://freepngimg.com/download/icon/thoughts/10268-woman-user-circle.png',
    }
];